import Head from "next/head";
import React from "react";

const MetaHeader = () => {
  return (
    <Head>
      <title>Hello</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default MetaHeader;
